// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5sHIYZ0AYd3ABfsTZgzpqADFHjcXUCAM',
    appId: '1:177370535188:web:db6cdd54656da940fc1e01',
    messagingSenderId: '177370535188',
    projectId: 'prova-sub-mobile',
    authDomain: 'prova-sub-mobile.firebaseapp.com',
    storageBucket: 'prova-sub-mobile.firebasestorage.app',
    measurementId: 'G-WW0D10L4HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADdHA7wL1ONjKvVR5VJFstj-f9Em0IUMM',
    appId: '1:177370535188:android:a06fcbbdd924a517fc1e01',
    messagingSenderId: '177370535188',
    projectId: 'prova-sub-mobile',
    storageBucket: 'prova-sub-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5aOBbiNvsy4Fzan7LzTBv927U4Y2Rjd8',
    appId: '1:177370535188:ios:14e60fe043d550c9fc1e01',
    messagingSenderId: '177370535188',
    projectId: 'prova-sub-mobile',
    storageBucket: 'prova-sub-mobile.firebasestorage.app',
    iosBundleId: 'com.example.provaSubMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5aOBbiNvsy4Fzan7LzTBv927U4Y2Rjd8',
    appId: '1:177370535188:ios:14e60fe043d550c9fc1e01',
    messagingSenderId: '177370535188',
    projectId: 'prova-sub-mobile',
    storageBucket: 'prova-sub-mobile.firebasestorage.app',
    iosBundleId: 'com.example.provaSubMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5sHIYZ0AYd3ABfsTZgzpqADFHjcXUCAM',
    appId: '1:177370535188:web:367388244772d8d4fc1e01',
    messagingSenderId: '177370535188',
    projectId: 'prova-sub-mobile',
    authDomain: 'prova-sub-mobile.firebaseapp.com',
    storageBucket: 'prova-sub-mobile.firebasestorage.app',
    measurementId: 'G-V1ZFDJVPE1',
  );

}